### ISSUE TITLE
Doesn't load on https installation of VRS

### ISSUE THREAD

**Issue by elmicha** [nitro999/vrs-overlays#1]
Hi,

thank you for these great overlays!

My VRS runs on a HTTPS site, and it didn't seem to load anything at first. In the Firefox web console I saw that it refused to load the http://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.3.1/leaflet-omnivore.min.js (in the body.html) - I changed it to //api.tiles.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.3.1/leaflet-omnivore.min.js and now it works.

It also couldn't find waypoints.kml, because it's named Waypoints.kml and the filesystem on Linux is case-sensitive. 

And the line

    <script type="text/javascript" src="leaflet.groupedlayercontrol.min.js.map"></script>

in the head.html produces an error message. This line should be removed - the browser will load the .map on its own if it needs the map.

Best regards...
  Michael

**Comment by nitro999** [comment]
Thank you for the feedback! Much appreciated!
